### ISSUE TITLE
ability to "extend" a layout

### ISSUE THREAD

**Issue by andrewrk** [forwardemail/email-templates#21]
There is a feature in some templating languages called "layout" or "blocks" which lets you do something like this:

```
blaho doaeudao d
utoaeduoesud soo 
ouoddo
{% block "block_name" %}
(this content is overridable)
{% end block %}
dbosoahueohunoeua
oaeuntdaoesudaoseuhaoeu
oeu
o
```

Then I could make a new template with something like this:

```
{% extends "layout_name" %}

{% block "block_name" %}
(I am overriding the content of the other block)
and I even have access to {{ block.super }}
{% end block %}
```

node-email-templates lacks this feature.

**Comment by remi2j** [comment]
It's 2019 and this is still very much needed

**Comment by niftylettuce** [comment]
@remi2j you could make a pull request you know, or R&D this further and provide a working example
