### ISSUE TITLE
Transport information

### ISSUE THREAD

**Issue by sonnyk22** [forwardemail/email-templates#321]
Thank you for this great library. 

My app works fine using the `email-templates v2.7.1`.  Now, I want to use the latest version.  I like the fact that in the latest version, I can send email with our requiring `nodemailer`.  However, I am not sure where I can pass-in my transport information as example below.

```
{
    host: 'smtp.domain.net', 
    port: 465,
    secure: true,
    auth: {
        user: '',
        pass: ''
    }
}
```

Thank you!

**Comment by niftylettuce** [comment]
You pass it as the `transport` option <https://github.com/niftylettuce/email-templates/blob/master/src/index.js#L83-L86>.

**Comment by sonnyk22** [comment]
I more quick question. 

I've gotten everything working nicely using the `email-templates v5.0 `as seen in the code below, but every time an email gets send (I do received them in my inbox), the browser opens up and shows me the output of my template with all the fields set, and the `text version` of the same template.  Is there a setting to turn this off in `Development `and `Production`?  

Thank you!

```
const config = {
    views: {
        root: root,
        options: {
            extension: 'hbs'
        }
    },
    message: {
        from: constants.EmailFrom
    },
    send: true,
    transport: {
        host: emailCreds.host,
        port: emailCreds.port,
        secure: emailCreds.secure,
        auth: {
            user: emailCreds.auth.user,
            pass: emailCreds.auth.pass
        },
        tls: {
            rejectUnauthorized: false
        }
    }
}

const email = new Email(config);
```

```
email
    .send({
        template: constants.TplEmailConfirmation,
        message: {
            to: 'email@somthing.net'
        },
        locals: {
            name: 'me'
        }
    })
    .then(() => {
        // code
    })
    .catch((err) => {
        // code
    });
```

**Comment by sonnyk22** [comment]
That was it!  Thank you!
