### ISSUE TITLE
(node:72191) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc()...

### ISSUE THREAD

**Issue by xfishernet** [forwardemail/email-templates#347]
I get an warning immediately after launch this string:
const Email = require('email-templates');

warning: (node:72191) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc()...

**Comment by josepgomes** [comment]
Same here!

**Comment by RikaXia** [comment]
用Node.js申请缓存buffer报DEP0005错误的解决方法：

before：new Buffer(myBase64Str, 'base64')
after：Buffer.from(myBase64Str, 'base64');
