### ISSUE TITLE
Attachment with stream not working on preview

### ISSUE THREAD

**Issue by antitoine** [forwardemail/email-templates#383]
Hi,
When I try to add an attachment to the email that comes from a stream, the attachment appears undefined in the preview in the browser (see the screenshot attached). However, when the mail is sent (I use AWS SES), the problem is not present and the attachment is correct.

![Sélection_016](https://user-images.githubusercontent.com/10686594/70992011-043f6400-20c9-11ea-86b2-0ad3039e51a8.png)

**Comment by niftylettuce** [comment]
I'm pretty sure this is due to JSON transport being the default for preview, care to submit a PR that fixes?

**Comment by niftylettuce** [comment]
I have just release `preview-email` v2.0.0 and version bumped it in `email-templates`, and released `email-templates` v7.0.0 🎉 

Ref:
* https://github.com/forwardemail/preview-email/releases/tag/v2.0.0
* https://github.com/forwardemail/email-templates/releases/tag/v7.0.0

**Comment by niftylettuce** [comment]
Stream attachments should work great now @antitoine 	- just version bump and install latest in your project

**Comment by antitoine** [comment]
Hi, thank you for the fix.
Indeed upgrade to v7.0.2 resolve the stream issue and the attachment is OK.
But now, the promise when we call `send` method is never released.
So I can't stay on the 7.0.2 for now...

**Comment by antitoine** [comment]
Maybe this need to be in another issue ?

**Comment by niftylettuce** [comment]
This should be fixed btw, not sure what your issues is @antitoine 	?

Can you give an example?  Sounds like a different problem?

**Comment by sgaestel** [comment]
Hi. Opened another issue for what @antitoine is describing, as facing the same issue: https://github.com/forwardemail/email-templates/issues/392

**Comment by niftylettuce** [comment]
See my comment here <https://github.com/forwardemail/email-templates/issues/392#issuecomment-634937183>.

You are using the nodemailer option incorrectly.  You cannot use jsonTransport with streams.  It does not support it.
