### ISSUE TITLE
Option "from" not working

### ISSUE THREAD

**Issue by Naterra** [forwardemail/email-templates#384]
```
const nodemailer = require('nodemailer');
const EmailTempl = require('email-templates');

const transporter = nodemailer.createTransport({
	host: process.env.EMAIL_SERVER,
	port: process.env.EMAIL_PORT || 25,
	secure: true,  
	auth: {
		user: process.env.EMAIL_USERNAME,
		pass: process.env.EMAIL_PASSWORD
	}
});

const emailServ = new EmailTempl({
	message:{ 
              from:"test@gmail.com", 
         },
	send: true,
	preview: false,
	htmlToText: false,
	transport: transporter,
});
```
I tried to use "from" as default parameter and from its instance, but sender value is always used from transporter.auth.user. What is wrong?

**Comment by niftylettuce** [comment]
Can you please provide a reproducible test or share more code that you are using?  Perhaps create a GitHub repo with code that is reproducible?  Are you on the latest version of `email-templates`?  `npm install email-templates@latest`
