### ISSUE TITLE
Subject encoding problem with french characters

### ISSUE THREAD

**Issue by marvinfretly** [forwardemail/email-templates#387]
Hello,

I'm creating mails using email-templates ans marko as a template engine.
So I've to create a file named subject.marko. Everything is going great but when I there is accent in my subject.marko, it got encoding problem and it look like that:
Subject: =?UTF-8?Q?Demande_d=27une_revue_d=27activit=C3=A9_?=
When the file look like:
`-- Demande d'une revue d'activité`

How is it possible to get the good encoding for my subject with accent?
I tried to add  'utf-8' to message.encoding but nothing happened.
Also removed subject.marko and made a new one to make sure there no encoding error on my file.

**Comment by niftylettuce** [comment]
I'm guessing your Marko template files are encoding the value or something.  Can you look into Marko docs to see how to disable or fix this?

**Comment by marvinfretly** [comment]
> I'm guessing your Marko template files are encoding the value or something. Can you look into Marko docs to see how to disable or fix this?

It's only happening on subject. If I use the same file for the body everything work

**Comment by marvinfretly** [comment]
> I'm guessing your Marko template files are encoding the value or something. Can you look into Marko docs to see how to disable or fix this?

There is no way to disable encoding.

It's only happening on subject. If I use the same file for the body everything work.

Maybe you can add a param to do this ?
https://ncona.com/2011/06/using-utf-8-characters-on-an-e-mail-subject/

**Comment by marvinfretly** [comment]
Ok I found the problem,
Everything is working well, it's only on the mail preview.
When I realy send the mail everything is working great
