### ISSUE TITLE
Special character in subject.pug

### ISSUE THREAD

**Issue by chhatch** [forwardemail/email-templates#390]
I trying to use a subject like 'Check this out: Foo & Bar' for a subject line in an email. Part of the subject comes from a variable, mySubject, with the value 'Foo & Bar'. My subject.pug looks like this:
 ``!= `Check this out: ${mySubject}` ``
But appears as `Check this out: Foo &amp; Bar` in my test emails.

I'm not sure what else to try. Any idea? Thanks!

**Comment by niftylettuce** [comment]
I'm not sure what your issue is - your expected and actual output seems to be the same?

**Comment by chhatch** [comment]
My bad, the subject appears as `Check this out: Foo &amp; Bar`

**Comment by niftylettuce** [comment]
What does your `subject.pug` look like?

It seems to me that since you're using `!=` it should work fine.  Is there some sort of encoding going on?  Try this to see output debug information in console when you try again:

```diff
- console.log('the subject mySubject was', mySubject)
!= `Check this out: ${mySubject}`
```

**Comment by niftylettuce** [comment]
Updated example*

**Comment by chhatch** [comment]
Here's what we got:
`the subject mySubject was  AHA CPR &amp; AED &amp; First Aid `
What's odd is that `span !{mysubject}` gives the expected output in html.pug

**Comment by niftylettuce** [comment]
I don't have time presently but ping me back in 24-48 hours if you still can't figure it out.

You can also run with `DEBUG=*` flag, or specifically `DEBUG=email-templates` or `DEBUG=preview-email`.

**Comment by chhatch** [comment]
Will do. You've been very helpful so far.

**Comment by chhatch** [comment]
I solved the issue by grabbing a value on the front end with `el.innerText` instead of `el.innerHTML`, which I should have been doing anyway. This was user error.
I really appreciate you helping me track down the issue so quickly.

**Comment by niftylettuce** [comment]
Great!

Obligatory sponsor link <https://github.com/sponsors/niftylettuce>
