### ISSUE TITLE
Prevent sending to unwanted domains

### ISSUE THREAD

**Issue by armellarcier** [forwardemail/email-templates#393]
I need my staging app to send e-mails only to a custom set of domains.

Is there a way to filter recipients (`to`) that would be cleaner that just parsing the string on my side? Can it be an array? I'd need a few pointers please.

Thanks in advance. BTW, this lib is really awesome.

**Comment by niftylettuce** [comment]
this is outside scope of this repo

look into my work on Forward Email https://github.com/forwardemail
