### ISSUE TITLE
Ampersand shows as &Amp; in subject

### ISSUE THREAD

**Issue by davidbarman** [forwardemail/email-templates#399]
The subject template doesn't seem to accept & characters.  If the & character is part of the template file explicitly or passed in a parameter variable it gets translated to &Amp; when the email is sent.

I have been unable to find a work around.

Any insight?

**Comment by niftylettuce** [comment]
your template engine is rendering it as escaped

for instance, with pug we do this:

```pug
!= 'Foo & Bar'
```

Instead of escaped:

```pug
= 'Foo & Bar'
```
