### ISSUE TITLE
i18n pluralization string JSON format

### ISSUE THREAD

**Issue by lanceschi** [forwardemail/email-templates#401]
Hello,

I'd like to have some clarification on i18n pluralization. If I store string likewise:
```json
{
  "%s dogLabel": {
    "one": "One dog",
    "other": "5 dogs"
  }
}
```
... and pluralize in a pug template with the following:
```pug
p= tn('%s dogLabel', 5)
```
I 'm getting **5 dogLabel**, whereas I'd like to get **5 dogs**.

Is there something wrong with my string JSON structure (taken more or less from [here][1])?

Thanks for the awesome lib!

[1]: https://github.com/mashpie/i18n-node#i18n__

**Comment by niftylettuce** [comment]
I've never used the pluralization nested stuff before, so I'm really not sure.  You could try writing a test in `@ladjs/i18n` at https://github.com/ladjs/i18n or something to get a better understanding if you wanted to push the ball on this one.

**Comment by niftylettuce** [comment]
PR welcome!
