### ISSUE TITLE
Preview shown but email not being sent

### ISSUE THREAD

**Issue by martinpiria** [forwardemail/email-templates#402]
I configured it the following way:

    const email = new Email({
        message: {  
            from: 'donotreply@edwardshavens.com'
        },
        options: {
            send: true
        },
        transport: {
            jsonTransport: true
        }
    });

The preview is being shown but the email not being sent to the mailbox, is there any configurations missing from the email server's side?

**Comment by niftylettuce** [comment]
`send` should be top level option, not nested in an object, see <https://github.com/forwardemail/email-templates#basic>

**Comment by martinpiria** [comment]
Changed it but still doesn't work, the receiving email box doesn't get the message? 
Feels like I'm missing configuration from the sending email server

**Comment by niftylettuce** [comment]
you have to configure a transport, see nodemailer docs

**Comment by ohabash** [comment]
I can see how to use `nodemailer` but how do i use that with `email-templates`?

**Comment by niftylettuce** [comment]
See the basic example in the README at https://github.com/forwardemail/email-templates#basic.

Instead of using this:

```js
  transport: {
    jsonTransport: true
  }
```

You would pass a [transport object for Nodemailer](https://nodemailer.com/transports/).

It can either be an instance from `createTransport` or a configuration object to create a new one https://github.com/forwardemail/email-templates/blob/master/src/index.js#L101-L104.

**Comment by ohabash** [comment]
Thank you!

This is how we did it for 365.

```  get transport() {
    return nodemailer.createTransport({
      service: 'Outlook365',
      auth: {
        user: "FROM@DOMAIN.AI",
        pass: "pass",
      },
    });
  }

  async init() {
    const root = path.join(__dirname, 'emails');
    this.Email = new Email({
      message: { from: this.from },
      send: true,
      views: { root },
      transport: this.transport,
    });
    return this;
    // this.repsonse = await this.send(); // DEV ONLY
  }
```

plus we had to do some [configs in 365](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission#use-the-microsoft-365-admin-center-to-enable-or-disable-smtp-auth-on-specific-mailboxes)
