### ISSUE TITLE
pug caching example for Next JS

### ISSUE THREAD

**Issue by stevenmunro** [forwardemail/email-templates#404]
Hi, would it be possible to have an example for having `cache-pug-templates` work with `email-templates` in a Next JS environment?

I have `email-templates` working from an endpoint which my contact form does a POST request to. `/pages/api/contact.js`. I'm unsure how to apply the [basic example](https://github.com/ladjs/cache-pug-templates) to Next JS.

**Comment by niftylettuce** [comment]
If you subscribe/watch the `cache-pug-templates` repo at https://github.com/ladjs/cache-pug-templates I will probably post more updates there.  PR welcome too!
