### ISSUE TITLE
Breaking change in v8

### ISSUE THREAD

**Issue by ddolcimascolo** [forwardemail/email-templates#410]
Hi guys,

Our build fails when upgrading from v7.2.0 to v8.0.0 because of the bumped `html-to-text` dependency. The outputted text is slightly different, mostly in newlines. This is totally OK as you released a major version, but maybe it's worth mentionning that in the [Breaking changes](https://github.com/forwardemail/email-templates#breaking-changes) section of the README ?

Regards,
David

**Comment by niftylettuce** [comment]
do you know what the default option is that we need to set to preserve existing usage and not break it?

**Comment by ddolcimascolo** [comment]
Sorry no 😔 I'm not even sure there's an option to set, maybe it's just the default behavior that was changed...

**Comment by niftylettuce** [comment]
what's the difference look like?

**Comment by ddolcimascolo** [comment]
AssertionError: expected 'Bonjour,\n\nUne nouvelle toolbox myToolbox a été créé par First Last\n\nCordialement,\n L\'équipe Stordata' to equal 'Bonjour,Une nouvelle toolbox myToolbox a été créé par First LastCordialement,\nL\'équipe Stordata'

```diff
+Bonjour,
+
+Une nouvelle toolbox myToolbox a été créé par First Last
+
+Cordialement,
+ L'équipe Stordata
-Bonjour,Une nouvelle toolbox myToolbox a été créé par First LastCordialement,
-L'équipe Stordata
```

The new version is actually far better, by the way. Closer to the rendered Html template.

**Comment by niftylettuce** [comment]
Oh that's awesome!  Yeah definitely looks better at a glance.  Maybe we just update the README?  Can you submit a PR and show an example or something?

**Comment by ddolcimascolo** [comment]
Will do 👍

**Comment by niftylettuce** [comment]
Thank you!
