### ISSUE TITLE
Breaking license

### ISSUE THREAD

**Issue by cythrawll** [forwardemail/email-templates#411]
So I should have looked more closely. But it seems the dependency chain of email-templates -> preview-email -> mailparser is breaking for me. as they relicensed mailparser to be EUPL 1.1. EUPL isn't a license I can use unfortunately, nor can I likely convince the powers that be to use it as it seems like the language in the license is a bit wishy washy legally when it comes to using it as a dependency, making it incompatible with many licenses.

mailparser does have MIT available behind a private pay repo :/.

I'd like to use email-templates still but with this license in the dependency chain i'm afraid I can no longer use it until the dependency is replaced with something a bit more friendly.

**Comment by niftylettuce** [comment]
Let me ping @andris9 by email about this

**Comment by niftylettuce** [comment]
I am releasing a fix shortly, sec

**Comment by niftylettuce** [comment]
https://github.com/forwardemail/email-templates/releases/tag/v8.0.1

**Comment by niftylettuce** [comment]
v8.0.1 released to npm
