### ISSUE TITLE
TypeScript out of date?

### ISSUE THREAD

**Issue by andrewmartin** [forwardemail/email-templates#416]
Is it me, or are your types incorrect? I'm using an (older) version of `@types/email-templates`, but not that old, and I can't find one up to date.

Main issue I'm seeing is that the third argument on `Email.renderAll` is not provided, which adds to a ton of confusion when consuming it.

**Comment by niftylettuce** [comment]
I don't maintain the types and don't support TypeScript, that must be maintained by someone else
