### ISSUE TITLE
Sending a Calendar Invite

### ISSUE THREAD

**Issue by vikalpjain** [forwardemail/email-templates#417]
I need to send a calendar invite. I'm using nodemailer for transportation. From whatever I read, I'm supposed to generate an iCal file and then attach it to the mail. I'm also supposed to add some extra information in headers so that Gmail/Outlook understand that there is an even attached. How do I achieve this using email-templates? I did not find a way to attach an iCal or options to change header. Any example will be great help.

**Comment by niftylettuce** [comment]
https://nodemailer.com/message/calendar-events/
