### ISSUE TITLE
can not access locals inside the pug file

### ISSUE THREAD

**Issue by Iamhashim92** [forwardemail/email-templates#418]
Hi, I have a email template i am trying to render. Here is the render config
`  email.render(root, {
      message: {
        to: 'iamhashim@yopmail.com',
      },
      locals: {
        locale: 'en',
        first_name: 'John',
        email: 'john@gmmail.com',
        reset_password_url: 'http://localhost:8080/forget',
      },
    }).then(console.log)
      .catch(console.error)`

and i am trying to access the locals like this
`p= `${t('email.forget.hi')}, ${first_name}``

locale is working fine but i can't access other locals, it is rendering the following tag
`<p>Hi, undefined</p>`
version- 8.0.3

**Comment by niftylettuce** [comment]
You have `email.forget.hi` not `email`?  Your code is not reproducible.

**Comment by Iamhashim92** [comment]
`email.forget.hi` is inside i18n `t` function which is working fine, i am not able to access `first_name`

**Comment by niftylettuce** [comment]
I need a reproducible test case / source code / repository
