### ISSUE TITLE
Ability to preview email in browser without actually sending it

### ISSUE THREAD

**Issue by tar-aldev** [forwardemail/email-templates#421]
Sorry to post this here, it is more like a feature request.

I came to some scenarious where I want to use this library only to preview emails in browser.
What I do now is
```
new Email({
      message: {
        // we will never actually send anything
        // so email can be any email
        from: ''
      },
      send: false,
```
But I still need to call `email.send`;

I know that it might be a little bit out of scope, but it would be really convenient to have a method inside `email`, something like `email.previewInBrowser` or something like this.

**Comment by niftylettuce** [comment]
PR would be welcome!
