### ISSUE TITLE
high severity vulnerabilities 

### ISSUE THREAD

**Issue by eliyabar** [forwardemail/email-templates#424]
Hey, there are some vulnerabilities in your packages that needed to be fixed.
Package: underscore
paths:
 email-templates > @ladjs/i18n > country-language >underscore
and
email-templates > @ladjs/i18n > i18n-locales >country-language > underscore 
Patched in   >=1.12.1

**Comment by bote795** [comment]
there is actually a pr in the country-language package for updating the package version which would then fix this i believe: https://github.com/bdswiss/country-language/pull/15
