### ISSUE TITLE
Dependencies outdated on v8.0.7

### ISSUE THREAD

**Issue by storkweb** [forwardemail/email-templates#427]
Hi,

I get this warning (node v16.3.0, yarn 1.23.0) 
"warning email-templates > @ladjs/i18n > i18n > messageformat@2.3.0: Package renamed as '@messageformat/core', see messageformat.github.io for more details. 'messageformat' will eventually provide a polyfill for Intl.MessageFormat, once it's been defined by Unicode & ECMA."

Could you, please, update your dependencies ?
Thanks a lot

**Comment by niftylettuce** [comment]
This is an issue in i18n, not this package https://github.com/mashpie/i18n-node/blob/master/package.json#L32

Once it's version bumped there we can resolve the issue here

Please submit a PR or file an issue there
