### ISSUE TITLE
[QUESTION] here is a way to use email framework like mjml ?

### ISSUE THREAD

**Issue by thib3113** [forwardemail/email-templates#429]
Hello, 

actually we use handlebars + mjml ( handlebars to template, and mjml to generate html responsive ) . 

So, here is a way to use your library, and setting up to insert mjml in the process ?

**Comment by niftylettuce** [comment]
You could fork `consolidate` and add it there, it might already be supported I'm not sure.

I'm sure you can write tests and hack a new feature for this or something.
