### ISSUE TITLE
absolute paths on WSL2

### ISSUE THREAD

**Issue by MidoloS** [forwardemail/email-templates#430]
**Is it possible to use absolute paths to access files from a WSL2 (Ubuntu) instance?**

I can see that the absolute paths are based on starting with "/"

so i tried the following solution

```js
return await sendMail({
    to: user.email,
    template: '/\\wsl$/Ubuntu/home/.../.../.../emails/users/welcome',
})
```

but it dropped the following error

![image](https://user-images.githubusercontent.com/22735268/128929851-20351f90-d556-4b9c-925e-9e8862bc3764.png)
```json
{ 
     "Error": "ENOENT: no such file or directory, stat '/\wsl$/Ubuntu/home/.../.../.../emails/users/welcome/text.pug'",
     "errno": "-2",
     "code": "ENOENT",
     "syscall": "stat",
     "path":
      "/\\wsl$/Ubuntu/home/.../.../.../emails/users/welcome/text.pug"
}
```

**Comment by niftylettuce** [comment]
Not sure why you have `\\`, that's your issue it seems.
