### ISSUE TITLE
Support for CSS variables/Sass/Less

### ISSUE THREAD

**Issue by asimkt** [forwardemail/email-templates#433]
Any plans to support any kind of CSS processors? Most of the CSS now a days have either any of the CSS variables or Sass supports. So if anybody wants to use the same styles from their web app, this is not possible now.

**Comment by niftylettuce** [comment]
Yes it is possible now.  A perfect example of how this is achieved is in the codebase for Forward Email.

https://github.com/forwardemail/forwardemail.net

Specifically see how we re-use the stylesheets here:

https://github.com/forwardemail/forwardemail.net/blob/master/emails/layout.pug#L10
