### ISSUE TITLE
Update to @ladjs/i18n@7.2.6

### ISSUE THREAD

**Issue by Enijar** [forwardemail/email-templates#434]
Since this package now fixes a deprecated package warning in npm (see [here](https://github.com/ladjs/i18n/issues/33)), this package needs to update @ladjs/i18n to 7.2.6.

**Comment by niftylettuce** [comment]
v8.0.9 released

https://github.com/forwardemail/email-templates/releases/tag/v8.0.9

thx for ping on this @Enijar
