### ISSUE TITLE
Compile errors from consolidate.js

### ISSUE THREAD

**Issue by engelkes-finstreet** [forwardemail/email-templates#435]
Hey! 

For reference: I am using version `8.0.10`.

I get a lot of compile errors after installing `email-templates.` To send emails I followed the first steps in the `README.md` and this is what my code looks like:

```ts
  const email = new Email({
    message: {
      from: "niftylettuce@gmail.com",
    },
    // uncomment below to send emails in development/test env:
    // send: true
    transport: {
      jsonTransport: true,
    },
  });

  email
    .send({
      template: "mars",
      message: {
        to: "elon@spacex.com",
      },
      locals: {
        name: "Elon",
      },
    })
    .then(console.log)
    .catch(console.error);
```

After starting my server I get the following compile errors:

```
> node_modules/consolidate/lib/consolidate.js:204:71: error: Could not resolve "velocityjs" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
    204 │ ...quires.velocityjs || (requires.velocityjs = require('velocityjs'));
        ╵                                                        ~~~~~~~~~~~~

  > node_modules/consolidate/lib/consolidate.js:493:43: error: Could not resolve "dustjs-linkedin" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
    493 │           engine = requires.dust = require('dustjs-linkedin');
        ╵                                            ~~~~~~~~~~~~~~~~~

  > node_modules/consolidate/lib/consolidate.js:629:59: error: Could not resolve "atpl" (mark it as external to exclude it from the bundle, or surround it with try/catch to handle the failure at run-time)
    629 │     var engine = requires.atpl || (requires.atpl = require('atpl'));

```

Any ideas how to fix this?

**Comment by niftylettuce** [comment]
Have you seen https://github.com/tj/consolidate.js/issues/334?

>  I finally figured it out by deleting the consolidate folder from node_modules, it then pointed to which component file was showing "import cons from "consolidate";" at the top.

**Comment by engelkes-finstreet** [comment]
I am using [Remix](https://remix.run/) and just tried it for a fresh install. I guess they are using Webpack.

**Comment by paninee** [comment]
Having the same issue on 9.0.0.

**Comment by adamgen** [comment]
I'm having the same issue using esbuild directly.

Why are all the dependencies marked as devDependencies? They are not installed locally using yarn 3, could this be the issue?

**Comment by supermar1010** [comment]
Any update here. I'm using email-templates in two nuxt3 projects without any issue. Now I'm trying to add it to a third one and I'm facing the aforementioned problems there. Any idea how to solve this?
