### ISSUE TITLE
Verbose console output

### ISSUE THREAD

**Issue by Mangatt** [forwardemail/email-templates#436]
Is there a way how to supress following console output in dev mode?

```
{
  envelope: { from: '...', to: [ '...' ] },
  messageId: '...',
  message: '...',
  originalMessage: {
    to: '...',
    from: '...',
    attachments: [ [Object] ],
    html: '...'
  }
}

**Comment by niftylettuce** [comment]
This is most likely from Nodemailer output.  See <https://nodemailer.com/smtp/#debug-options>.

**Comment by Mangatt** [comment]
That's not it, message is present even with `debug: false`. This has to be connected to `email-templates`, when we use `Nodemailer` directly, everything is fine.
